##swiftmailer:
##   url: '%env(MAILER_URL)%'
##   spool: { type: 'memory' }


swiftmailer:
      spool:     { type: memory }
      transport: smtp
      host:      smtp.mailtrap.io
      username:  c751f7e3e2a39b
      password:  188381660aad77
      auth_mode: cram-md5
      port: 2525