<?php

namespace App\Repository;

/**
 * ServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesRepository extends \Doctrine\ORM\EntityRepository
{

    public function findServiceWithImage()
    {

        $qb = $this->createQueryBuilder('s');

        $qb->leftJoin('s.image', 'i')->addSelect('i');

        return $qb->getQuery()
            ->getResult();

    }




}
