<?php

namespace App\Repository;

/**
 * StageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageRepository extends \Doctrine\ORM\EntityRepository
{

    public function stageWhithProvider($slug)
    {

        $qb = $this->createQueryBuilder('s');

        $qb->leftJoin('s.provider', 'p')->addSelect('p')
            ->leftJoin('p.services', 'services')->addSelect('services')
            ->andWhere('s.slug LIKE :slug')
            ->setParameter('slug', $slug);

        return $qb->getQuery()
            ->getSingleResult();


    }

    public function stagesProvider($id){

        $qb = $this->createQueryBuilder('u')
            ->leftJoin('u.provider', 'p')->addSelect('p')
            ->andWhere("p.id LIKE :id")
            ->setParameter('id',$id);

        return $qb
            ->getQuery()
            ->getResult();
    }

}
